name: Build JiYuTrainer

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
<<<<<<< HEAD

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild JiYuTrainer.sln /p:Configuration=Release /p:Platform=x64
=======
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Build Solution
      run: msbuild /p:Configuration=Release
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: JiYuTrainer-Build
        path: |
          **/bin/Release/
          !**/obj/
>>>>>>> 9e22939909b2aa1d3f0c7fa171643bdecf7cfae2
